#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  8 11:38:01 2020

@author: hannahmacdonell
"""
import csv
import random
import string
#Inventory(itemID, userID, listPrice, datePosted, category, postType, itemDescription, keywords, condition)


l = []
c = open("users.txt", "r")
for line in c:
    l.append(line.split(',')[0])
c.close()



idd = []
for i in range (7000):
    if i >= 0 and i <= 999: 
        idd.append([(i+1000000),'TECH']) 
    if i >=1000 and i<=1999:
        idd.append([(i+1000000),'HOME'])
    if i >= 2000 and i <= 2999: 
        idd.append([(i+1000000),'CLOT'])
    if i >= 3000 and i<=3999:
        idd.append([(i+1000000),'SPOR'])
    if i >= 4000 and i <=4999:
        idd.append([(i+1000000),'TEXT'])
    if i >=5000 and i<=5999:
        idd.append([(i+1000000),'MUSI'])        
    if i >=6000 and i<=6999:
        idd.append([(i+1000000),'MISC'])
        
con = []
c = open("condition.txt", "r")
for line in c:
    con.append(line.split(',')[0])
c.close()

col = []
c = open("colour.txt", "r")
for line in c:
    col.append(line.split(',')[0].strip().split('\n')[0])
c.close()

print(len(l))
print(len(idd))


day = ['01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','15','16','17','18','19','20','21','22','23','24','25','26'] 
month = ['00','01','02','03','04','05','06','07','08','09','10','11','12']

with open('inventory.csv', mode='w') as data_file:
    data_writer = csv.writer(data_file, delimiter=',')
    data_writer.writerow(['itemID', 'userID', 'listPrice', 'datePosted', 'category', 'postType', 'itemDescription', 'keywords', 'condition'])
    for x in range(7000):
        dnum = random.randint(0,25)
        m = random.randint(0,11)
        y = str(random.randint(2015,2020))
        d = day[dnum]+month[m]+str(y)
        if  x%2 !=0:
            listPrice = '$'+str(random.randint(10,120))+'.00'
            postType = 'B'
        else:
            listPrice = 0
            postType = 'L'
        description = ''.join([random.choice(string.ascii_letters + string.digits) for n in range(60)])
        data_writer.writerow([idd[x][0],l[random.randint(0,999)],listPrice,
                              d, idd[x][1],
                              postType, description,
                              col[random.randint(0,len(col)-1)],
                              con[random.randint(0,len(con)-1)]])
data_file.close()
