#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Mar  4 19:29:47 2020

@author: hannahmacdonell
"""
import csv
import random 
#ISBN(ISBN, textName, author, edition)

a = []
outF = open("ISBN.txt", "r")
for line in outF:
    a.append(line.strip().split('\n')[0])
outF.close()

b = []
outF = open("textbook.txt", "r")
for line in outF:
    b.append(line.strip().split('\n')[0])
outF.close()


c = []
outF = open("author.txt", "r")
for line in outF:
    c.append(line.strip().split('\n')[0])
outF.close()

d = []
for x in range(1000):
    d.append(random.randint(1,20))

with open('ISBN.csv', mode='w') as data_file:
    data_writer = csv.writer(data_file, delimiter=',')
    data_writer.writerow(['ISNB','textName','author','edition'])
    i=0
    while(i<1000):
        data_writer.writerow([a[i],b[i],c[random.randint(0,len(c)-1)],random.randint(1,20)])
        i = i+1
        
data_file.close()

