#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Mar  8 09:27:37 2020

@author: hannahmacdonell
"""

#H: Technology(itemID, tBrand, device, serialNo) 

import random
import csv


d = []
c = open("device.txt", "r")
for line in c:
    d.append(line.strip().split('\n')[0])
c.close()
    

l = []
c = open("tBrand.txt", "r")
for line in c:
    l.append(line.strip().split('\n')[0])
c.close()
    

with open('tech.csv', mode='w') as data_file:
    data_writer = csv.writer(data_file, delimiter=',')
    data_writer.writerow(['tBrand','Device','SerialNo'])
    for x in range(1000):
        data_writer.writerow([l[random.randint(0,len(l)-1)],d[random.randint(0,len(d)-1)],str(random.randint(4123456,9123456))])
        
data_file.close()
